//! Travsr Phase B — Scala semantic analysis via SemanticDB.
//!
//! SemanticDB is built into the Scala compiler (scalac 2.13+ / Scala 3). This
//! sidecar injects a temporary sbt settings file enabling SemanticDB, runs
//! `sbt compile`, then parses the resulting `.semanticdb` protobuf files to
//! extract ref/call edges.
//!
//! Why not scip-scala? scip-scala is not published to any accessible registry
//! (Maven Central, Sonatype, or GitHub Releases) and cannot be installed
//! automatically. SemanticDB is a first-class feature of every modern sbt
//! project.
//!
//! ## Sandbox class: RequiresElevated (ADR-017 Rule 1)
//!
//! `sbt compile` resolves dependencies from Maven/sbt plugin repositories.
//!
//! ```text
//! travsr lang approve scala \
//!   --approved-by <pse-handle> \
//!   --reason "sbt dependency resolution for Scala semantic analysis" \
//!   --permitted-hosts repo1.maven.org,repo.maven.apache.org,repo.scala-sbt.org
//! travsr lang install scala
//! ```

use anyhow::Context as _;
use std::collections::{HashMap, VecDeque};
use std::io::Read;
use std::path::{Path, PathBuf};
use travsr_core::{Edge, EdgeKind, Node, NodeId, ScipRef, VName};
use travsr_plugin_sdk::{
    run_plugin, InvokeRequest, InvokeResponse, ParseRequest, ParseResponse, Plugin,
};

const TIMEOUT_SECS: u64 = 600;
const SETTINGS_FILE: &str = ".travsr-semanticdb.sbt";
const SETTINGS_CONTENT: &str =
    "// Auto-generated by travsr Phase B — safe to delete.\nsemanticdbEnabled := true\n";

struct ScalaPhaseB;

impl Plugin for ScalaPhaseB {
    fn language(&self) -> travsr_core::Language {
        travsr_core::Language::Scala
    }
    fn extensions(&self) -> &[&str] {
        &["scala", "sc"]
    }
    fn supports_phase_b(&self) -> bool {
        sbt_available()
    }
    fn parse(&self, _req: &ParseRequest) -> ParseResponse {
        ParseResponse::default()
    }
    fn invoke_phase_b(&self, req: &InvokeRequest) -> InvokeResponse {
        match run_semanticdb(&req.root, req.corpus.as_str()) {
            Ok(resp) => resp,
            Err(e) => {
                tracing::warn!("semanticdb failed for {}: {e}", req.root.display());
                InvokeResponse::default()
            }
        }
    }
}

static SBT_BIN: std::sync::OnceLock<Option<PathBuf>> = std::sync::OnceLock::new();

fn find_sbt() -> Option<&'static PathBuf> {
    SBT_BIN
        .get_or_init(|| {
            // 1. PATH / ~/.travsr/bin, PATHEXT-aware — a bare `d.join("sbt").exists()`
            // probe finds the POSIX shim sbt ships alongside `sbt.bat` on Windows (a
            // `#!/usr/bin/env bash` script CreateProcess cannot run), the same bug
            // shape as K6/#502. `tool_path` prefers `sbt.bat` there and degrades to
            // the bare name on unix, with no JVM spawn either way.
            if let Some(p) = travsr_core::exec::tool_path("sbt") {
                return Some(p);
            }
            let home = std::env::var_os("HOME").map(PathBuf::from)?;
            // 2. SDKMAN! — sdk install sbt
            let candidate = home.join(".sdkman/candidates/sbt/current/bin/sbt");
            if candidate.exists() {
                return Some(candidate);
            }
            // 3. Coursier on Linux — cs install sbt
            let candidate = home.join(".local/share/coursier/bin/sbt");
            if candidate.exists() {
                return Some(candidate);
            }
            // 4. Coursier on macOS
            let candidate = home.join("Library/Application Support/Coursier/bin/sbt");
            candidate.exists().then_some(candidate)
        })
        .as_ref()
}

fn sbt_available() -> bool {
    find_sbt().is_some()
}

/// Walk up to `max_depth` levels to find the directory containing `build.sbt`.
fn find_sbt_root(root: &Path, max_depth: usize) -> Option<PathBuf> {
    let mut queue: VecDeque<(PathBuf, usize)> = VecDeque::new();
    queue.push_back((root.to_path_buf(), 0));
    while let Some((dir, depth)) = queue.pop_front() {
        if dir.join("build.sbt").is_file() {
            return Some(dir);
        }
        if depth < max_depth {
            if let Ok(entries) = std::fs::read_dir(&dir) {
                for e in entries.flatten() {
                    let p = e.path();
                    if p.is_dir() {
                        let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                        if !matches!(name, "target" | ".git" | "node_modules" | ".travsr") {
                            queue.push_back((p, depth + 1));
                        }
                    }
                }
            }
        }
    }
    None
}

/// Walk `target/` collecting all `*.semanticdb` files (any depth).
fn find_semanticdb_files(sbt_root: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut queue: VecDeque<PathBuf> = VecDeque::new();
    queue.push_back(sbt_root.join("target"));
    while let Some(dir) = queue.pop_front() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                queue.push_back(p);
            } else if p.extension().and_then(|e| e.to_str()) == Some("semanticdb") {
                found.push(p);
            }
        }
    }
    found
}

fn debug_log(msg: &str) {
    if let Some(home) = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
    {
        let dir = home.join(".sbt");
        let _ = std::fs::create_dir_all(&dir);
        use std::io::Write;
        if let Ok(mut f) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(dir.join("scala-wrapper-debug.log"))
        {
            let _ = writeln!(f, "{msg}");
        }
    }
}

/// `InvokeRequest::root` arrives on Windows already canonicalized with the
/// extended-length verbatim prefix, e.g. `\\?\D:\repo`, not a plain drive
/// path (same shape as the Kotlin wrapper's `strip_windows_verbatim_prefix`,
/// see its doc comment for the general mechanism). Left unstripped and handed
/// to `Command::current_dir`, sbt's own `bootServerSocket` — which even
/// `--server` mode runs, to bind the IPC socket other clients could still
/// attach to — calls `Path.toRealPath()` on the CWD to derive the socket's
/// identity, and `WindowsLinkSupport.getRealPath` throws
/// `AccessDeniedException` on a `\\?\`-prefixed path under the sandbox (empty
/// stdout, no compile ever attempted). A no-op when the prefix isn't present.
fn strip_windows_verbatim_prefix(s: &str) -> &str {
    s.strip_prefix(r"\\?\UNC\")
        .or_else(|| s.strip_prefix(r"\\?\"))
        .unwrap_or(s)
}

fn run_semanticdb(root: &Path, corpus: &str) -> anyhow::Result<InvokeResponse> {
    let root_str = root.display().to_string();
    let root = Path::new(strip_windows_verbatim_prefix(&root_str));
    debug_log("run_semanticdb: enter");
    let sbt_bin = find_sbt().ok_or_else(|| {
        anyhow::anyhow!(
            "sbt not found — install via SDKMAN! (sdk install sbt), \
             Coursier (cs install sbt), or Homebrew (brew install sbt)"
        )
    })?;
    debug_log(&format!("sbt_bin={}", sbt_bin.display()));

    let sbt_root = find_sbt_root(root, 4)
        .ok_or_else(|| anyhow::anyhow!("no build.sbt found under {}", root.display()))?;
    tracing::info!(sbt_root = %sbt_root.display(), "found sbt project root");
    debug_log(&format!("sbt_root={}", sbt_root.display()));

    let settings_path = sbt_root.join(SETTINGS_FILE);
    if let Err(e) = std::fs::write(&settings_path, SETTINGS_CONTENT) {
        debug_log(&format!("settings write failed: {e:?}"));
        return Err(e).with_context(|| format!("writing {}", settings_path.display()));
    }
    debug_log("settings write OK");

    debug_log(&format!(
        "canonicalize(sbt_root) -> {:?}",
        std::fs::canonicalize(&sbt_root)
    ));
    debug_log(&format!(
        "env HOME={:?} USERPROFILE={:?} LOCALAPPDATA={:?} APPDATA={:?} TEMP={:?} TMP={:?} PATH={:?}",
        std::env::var("HOME"),
        std::env::var("USERPROFILE"),
        std::env::var("LOCALAPPDATA"),
        std::env::var("APPDATA"),
        std::env::var("TEMP"),
        std::env::var("TMP"),
        std::env::var("PATH"),
    ));
    {
        use std::net::ToSocketAddrs;
        let resolved = "repo1.maven.org:443"
            .to_socket_addrs()
            .map(|it| it.collect::<Vec<_>>());
        debug_log(&format!("dns resolve repo1.maven.org:443 -> {resolved:?}"));
        if let Ok(addrs) = &resolved {
            if let Some(addr) = addrs.first() {
                let conn =
                    std::net::TcpStream::connect_timeout(addr, std::time::Duration::from_secs(10));
                debug_log(&format!(
                    "tcp connect {addr} -> ok={} err={:?}",
                    conn.is_ok(),
                    conn.err()
                ));
            }
        }
    }

    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(TIMEOUT_SECS);
    let result = run_sbt_compile(&sbt_root, sbt_bin, deadline);
    debug_log(&format!("run_sbt_compile: {result:?}"));

    let _ = std::fs::remove_file(&settings_path);

    let (status, stderr_out) = result?;
    anyhow::ensure!(
        status.success(),
        "sbt compile exited with {status}:\n{stderr_out}"
    );

    let semanticdb_files = find_semanticdb_files(&sbt_root);
    debug_log(&format!(
        "find_semanticdb_files under {} -> {:?}",
        sbt_root.join("target").display(),
        semanticdb_files
    ));
    tracing::info!("found {} .semanticdb files", semanticdb_files.len());

    let mut all_docs = Vec::new();
    for path in &semanticdb_files {
        let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;
        all_docs.extend(parse_text_documents(&bytes));
    }

    Ok(build_edges(&all_docs, corpus))
}

fn run_sbt_compile(
    sbt_root: &Path,
    sbt_bin: &Path,
    deadline: std::time::Instant,
) -> anyhow::Result<(std::process::ExitStatus, String)> {
    // #S3: plain `sbt compile` uses sbt 2.x's thin-client/background-server
    // split (`sbtn`), which talks to the server over a loopback socket. Windows
    // AppContainer blocks loopback for a sandboxed process unless separately
    // exempted via NetworkIsolationSetAppContainerConfig (a systemwide,
    // admin-only setting travsr has no business changing per invoke) — the
    // client's connect fails silently and it returns a false "success" in
    // under a second with no compile ever run. `--server` runs sbt itself in
    // the foreground as one process (no client/server IPC at all), so it works
    // the same whether sandboxed or not; confirmed identical real compiles
    // (real elapsed time, `.semanticdb` output) with and without the sandbox.
    let mut child = std::process::Command::new(sbt_bin)
        .args(["--server", "compile"])
        .current_dir(sbt_root)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("failed to spawn sbt")?;

    // Drain stdout/stderr on their own threads *while* sbt runs. sbt compile emits
    // far more output than an OS pipe buffer holds; reading only after exit
    // deadlocks (sbt blocks writing to a full pipe while we block waiting for it to
    // exit). The reader threads finish at EOF, when sbt exits or is killed.
    let drain = |stream: Option<Box<dyn std::io::Read + Send>>| {
        std::thread::spawn(move || {
            let mut buf = String::new();
            if let Some(mut s) = stream {
                let _ = s.read_to_string(&mut buf);
            }
            buf
        })
    };
    let out_h = drain(
        child
            .stdout
            .take()
            .map(|s| Box::new(s) as Box<dyn std::io::Read + Send>),
    );
    let err_h = drain(
        child
            .stderr
            .take()
            .map(|s| Box::new(s) as Box<dyn std::io::Read + Send>),
    );

    let status = loop {
        match child.try_wait().context("polling sbt")? {
            Some(s) => break s,
            None if std::time::Instant::now() >= deadline => {
                let _ = child.kill();
                anyhow::bail!("sbt compile timed out after {TIMEOUT_SECS}s");
            }
            None => std::thread::sleep(std::time::Duration::from_millis(500)),
        }
    };

    let stdout_out = out_h.join().unwrap_or_default();
    let stderr_out = err_h.join().unwrap_or_default();
    debug_log(&format!("stdout=[{stdout_out}]"));
    Ok((status, stderr_out))
}

// ── Minimal SemanticDB protobuf parser ───────────────────────────────────────
// SemanticDB file = serialised TextDocuments proto (wire format).
// We only decode fields needed for ref/call edge extraction.

#[derive(Debug, Default)]
struct TextDocument {
    uri: String,
    symbols: Vec<SymbolInfo>,
    occurrences: Vec<Occurrence>,
}

#[derive(Debug)]
struct SymbolInfo {
    symbol: String,
    kind: u32,
}

#[derive(Debug)]
struct Occurrence {
    start_line: u32,
    end_line: u32,
    symbol: String,
    role: u32, // 1 = REFERENCE, 2 = DEFINITION
    // #299 F3: whether this occurrence actually carried a Range message.
    // SemanticDB ranges are 0-based, so a genuine line-1 occurrence and an
    // absent range both decode to start_line == 0 — this bit disambiguates
    // them so a range-less occurrence is never emitted as a phantom `path:1`.
    has_range: bool,
}

fn read_varint(data: &[u8], pos: &mut usize) -> Option<u64> {
    let mut result = 0u64;
    let mut shift = 0u32;
    loop {
        let b = *data.get(*pos)?;
        *pos += 1;
        result |= ((b & 0x7f) as u64) << shift;
        if b & 0x80 == 0 {
            return Some(result);
        }
        shift += 7;
        if shift >= 64 {
            return None;
        }
    }
}

fn skip_field(data: &[u8], pos: &mut usize, wire_type: u64) {
    match wire_type {
        0 => {
            read_varint(data, pos);
        }
        1 => *pos = pos.saturating_add(8).min(data.len()),
        2 => {
            if let Some(len) = read_varint(data, pos) {
                *pos = pos.saturating_add(len as usize).min(data.len());
            }
        }
        5 => *pos = pos.saturating_add(4).min(data.len()),
        _ => *pos = data.len(), // unknown wire type — stop parsing
    }
}

/// Parse both start_line (field 1) and end_line (field 3) from a SemanticDB Range message.
fn parse_range_lines(data: &[u8]) -> (u32, u32) {
    let mut pos = 0;
    let mut start_line = 0u32;
    let mut end_line = 0u32;
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        if wtype == 0 {
            let val = read_varint(data, &mut pos).unwrap_or(0);
            match field {
                1 => start_line = val as u32,
                3 => end_line = val as u32,
                _ => {}
            }
        } else {
            skip_field(data, &mut pos, wtype);
        }
    }
    (start_line, end_line)
}

fn parse_occurrence(data: &[u8]) -> Occurrence {
    let mut pos = 0;
    let mut occ = Occurrence {
        start_line: 0,
        end_line: 0,
        symbol: String::new(),
        role: 0,
        has_range: false,
    };
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                // range — extract both start_line and end_line
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                let (sl, el) = parse_range_lines(&data[pos..end]);
                occ.start_line = sl;
                occ.end_line = if el > 0 { el } else { sl }; // single-line: end == start
                occ.has_range = true;
                pos = end;
            }
            (2, 2) => {
                // symbol string
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    occ.symbol = s.to_string();
                }
                pos = end;
            }
            (3, 0) => {
                // role
                occ.role = read_varint(data, &mut pos).unwrap_or(0) as u32;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    occ
}

fn parse_sym_info(data: &[u8]) -> SymbolInfo {
    let mut pos = 0;
    let mut info = SymbolInfo {
        symbol: String::new(),
        kind: 0,
    };
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    info.symbol = s.to_string();
                }
                pos = end;
            }
            (3, 0) => {
                info.kind = read_varint(data, &mut pos).unwrap_or(0) as u32;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    info
}

fn parse_text_document(data: &[u8]) -> TextDocument {
    let mut pos = 0;
    let mut doc = TextDocument::default();
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (2, 2) => {
                // uri
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    doc.uri = s.to_string();
                }
                pos = end;
            }
            (5, 2) => {
                // symbols (repeated SymbolInformation)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                doc.symbols.push(parse_sym_info(&data[pos..end]));
                pos = end;
            }
            (6, 2) => {
                // occurrences (repeated SymbolOccurrence)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                doc.occurrences.push(parse_occurrence(&data[pos..end]));
                pos = end;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    doc
}

fn parse_text_documents(data: &[u8]) -> Vec<TextDocument> {
    let mut pos = 0;
    let mut docs = Vec::new();
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                // documents (repeated TextDocument)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                docs.push(parse_text_document(&data[pos..end]));
                pos = end;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    docs
}

// ── Edge construction ─────────────────────────────────────────────────────────

// SemanticDB Kind enum values (scalameta/semanticdb.proto)
const KIND_FIELD: u32 = 2;
const KIND_METHOD: u32 = 3;
const KIND_OBJECT: u32 = 10;
const KIND_PACKAGE_OBJECT: u32 = 12;
const KIND_CLASS: u32 = 13;
const KIND_TRAIT: u32 = 14;
const KIND_MACRO: u32 = 22;

fn is_container_kind(kind: u32) -> bool {
    matches!(
        kind,
        KIND_FIELD
            | KIND_METHOD
            | KIND_OBJECT
            | KIND_PACKAGE_OBJECT
            | KIND_CLASS
            | KIND_TRAIT
            | KIND_MACRO
    )
}

fn kind_str(kind: u32) -> &'static str {
    match kind {
        KIND_FIELD => "field",
        KIND_METHOD | KIND_MACRO => "method",
        KIND_OBJECT | KIND_PACKAGE_OBJECT => "object",
        KIND_CLASS => "class",
        KIND_TRAIT => "trait",
        _ => "sym",
    }
}

fn is_stdlib_symbol(symbol: &str) -> bool {
    symbol.starts_with("scala/")
        || symbol.starts_with("java/")
        || symbol.starts_with("javax/")
        || symbol.starts_with("_root_/")
        || symbol.starts_with("android/")
}

/// A SemanticDB anonymous local (`local0`, `local12`): intra-method noise with
/// no navigable identity, like SCIP's `local N`. Dropped so it never surfaces
/// as a graph node.
fn is_local_symbol(symbol: &str) -> bool {
    symbol
        .strip_prefix("local")
        .is_some_and(|rest| !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()))
}

/// A parameter descriptor (`…greet().(name)`, terminal `(name)` ending in `)`).
/// Signature-local noise the scip-reader path already drops; mirror it here so
/// scala matches the other languages and never emits a raw parameter node.
fn is_parameter_descriptor(symbol: &str) -> bool {
    symbol.ends_with(')')
}

/// Symbols that must not become graph nodes or edge endpoints: stdlib, anonymous
/// locals, and parameter descriptors.
fn is_noise_symbol(symbol: &str) -> bool {
    is_stdlib_symbol(symbol) || is_local_symbol(symbol) || is_parameter_descriptor(symbol)
}

fn sdb_vname(symbol: &str, path: &str, corpus: &str) -> VName {
    VName::new(corpus, "", path, "scala", format!("sdb:{symbol}"))
}

fn build_edges(docs: &[TextDocument], corpus: &str) -> InvokeResponse {
    let mut nodes = Vec::new();
    let mut edges = Vec::new();
    // #299 S1: occurrence records (path:line) so the daemon can populate
    // edge_sites and answer find_references. Without these, only structural
    // ref/call edges exist and find_references returns 0.
    let mut refs: Vec<ScipRef> = Vec::new();

    // Pre-pass: global symbol → definition NodeId, so a reference in one file to a
    // symbol defined in another resolves to the correct callee node (the per-doc
    // edge builder below keys dst on the *reference's* uri, which is wrong across
    // files; refs use this map instead).
    let mut def_ids: HashMap<String, NodeId> = HashMap::new();
    for doc in docs {
        for sym in &doc.symbols {
            if is_noise_symbol(&sym.symbol) {
                continue;
            }
            def_ids
                .entry(sym.symbol.clone())
                .or_insert_with(|| sdb_vname(&sym.symbol, &doc.uri, corpus).id());
        }
    }

    for doc in docs {
        let uri = &doc.uri;

        // symbol → kind map
        let kind_map: HashMap<&str, u32> = doc
            .symbols
            .iter()
            .map(|s| (s.symbol.as_str(), s.kind))
            .collect();

        // DEF occurrences for container symbols, sorted by start_line ascending
        let mut def_containers: Vec<(u32, &str)> = doc
            .occurrences
            .iter()
            .filter(|o| o.role == 2) // DEFINITION
            .filter(|o| {
                let kind = kind_map.get(o.symbol.as_str()).copied().unwrap_or(0);
                is_container_kind(kind)
            })
            .map(|o| (o.start_line, o.symbol.as_str()))
            .collect();
        def_containers.sort_by_key(|(line, _)| *line);

        // Emit a node for every user-defined symbol
        for sym in &doc.symbols {
            if is_noise_symbol(&sym.symbol) {
                continue;
            }
            let vname = sdb_vname(&sym.symbol, uri, corpus);
            // #299 F3: only trust a DEFINITION occurrence that carried a real
            // range. A range-less def would decode to start_line 0 → a bogus
            // line-0 span that can wrongly enclose later occurrences; emit the
            // node without a line instead so it is never a false enclosing span.
            let def_occ = doc
                .occurrences
                .iter()
                .find(|o| o.role == 2 && o.symbol == sym.symbol && o.has_range);
            let mut node = Node::new(vname, kind_str(sym.kind));
            if let Some(o) = def_occ {
                node = node
                    .with_line(o.start_line + 1)
                    .with_end_line(o.end_line + 1);
            }
            nodes.push(node);
        }

        // ref/call edges: for each user REFERENCE find enclosing DEF container
        for occ in &doc.occurrences {
            if occ.role != 1 {
                continue; // only REFERENCEs
            }
            if is_noise_symbol(&occ.symbol) {
                continue;
            }
            // #299 F3: a range-less reference occurrence has no real position;
            // skip it so it is never recorded as a phantom `path:1` site (and
            // its enclosing-container lookup below is meaningless without a line).
            if !occ.has_range {
                continue;
            }

            // #299 S1 + R6: emit an occurrence record for this reference so the
            // daemon attributes it to its enclosing function (positional span
            // lookup in write_scip_attributed_batch) and records an edge_sites
            // row. A ScipRef, when produced, SUPERSEDES the structural enclosing
            // edge below: emitting both creates a spurious second ref/call caller
            // because the structural edge derives its src from the def-container
            // heuristic, not the positional span, so the two rows differ under
            // ON CONFLICT(src, dst, kind). The structural edge also mis-keyed its
            // dst on the *reference's* uri instead of the definition's (#597),
            // dangling for every cross-file reference; routing resolved refs
            // solely through the ScipRef (callee_id keyed on the def uri via
            // def_ids) removes that dangling too.
            if let Some(&callee_id) = def_ids.get(&occ.symbol) {
                refs.push(ScipRef {
                    caller_path: uri.clone(),
                    caller_line: occ.start_line + 1,
                    callee_id,
                    // is_call (#650): no call/non-call signal available here;
                    // preserve prior behavior / wire default (default_true).
                    is_call: true,
                });
                continue;
            }

            // Fallback only when the callee has no in-corpus definition (no
            // ScipRef, no def node): a best-effort enclosing → reference edge.
            // It has no resolvable callee node and is dropped by the daemon's
            // fail-closed callee gate; kept minimal to avoid a wider behavioral
            // change than R6 requires.
            let Some((_, enc_sym)) = def_containers
                .iter()
                .rev()
                .find(|(line, _)| *line <= occ.start_line)
            else {
                continue;
            };

            if *enc_sym == occ.symbol {
                continue; // skip self-ref
            }

            let src_vname = sdb_vname(enc_sym, uri, corpus);
            let dst_vname = sdb_vname(&occ.symbol, uri, corpus);
            edges.push(Edge::new(src_vname.id(), dst_vname.id(), EdgeKind::RefCall));
        }
    }

    let edge_count = edges.len();
    let node_count = nodes.len();
    tracing::info!(
        nodes = node_count,
        edges = edge_count,
        "semanticdb: built graph"
    );

    InvokeResponse {
        nodes,
        edges,
        refs,
        unresolved_calls: Vec::new(),
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("travsr_lang_scala=info".parse().unwrap()),
        )
        .init();

    run_plugin(ScalaPhaseB);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sym(symbol: &str, kind: u32) -> SymbolInfo {
        SymbolInfo {
            symbol: symbol.to_string(),
            kind,
        }
    }

    fn occ(symbol: &str, line: u32, role: u32) -> Occurrence {
        Occurrence {
            start_line: line,
            end_line: line,
            symbol: symbol.to_string(),
            role,
            has_range: true,
        }
    }

    // R6 + #597: a cross-file reference to a defined symbol is carried solely by
    // a ScipRef whose callee_id is keyed on the DEFINITION's uri; no structural
    // RefCall edge (which would mis-key its dst on the reference's uri and
    // duplicate the positional edge) is emitted.
    #[test]
    fn resolved_cross_file_ref_emits_scipref_only() {
        let docs = vec![
            TextDocument {
                uri: "A.scala".to_string(),
                symbols: vec![
                    sym("a/Caller#", KIND_CLASS),
                    sym("a/Caller#call().", KIND_METHOD),
                ],
                occurrences: vec![
                    occ("a/Caller#", 0, 2),
                    occ("a/Caller#call().", 1, 2),
                    // reference to a symbol defined in B.scala
                    occ("b/Callee#target().", 3, 1),
                ],
            },
            TextDocument {
                uri: "B.scala".to_string(),
                symbols: vec![
                    sym("b/Callee#", KIND_CLASS),
                    sym("b/Callee#target().", KIND_METHOD),
                ],
                occurrences: vec![occ("b/Callee#", 0, 2), occ("b/Callee#target().", 1, 2)],
            },
        ];

        let resp = build_edges(&docs, "testcorpus");

        // exactly one ScipRef, callee keyed on the DEFINITION uri (B.scala)
        let callee_id = sdb_vname("b/Callee#target().", "B.scala", "testcorpus").id();
        assert_eq!(resp.refs.len(), 1);
        assert_eq!(resp.refs[0].caller_path, "A.scala");
        assert_eq!(resp.refs[0].caller_line, 4); // 3 + 1
        assert_eq!(resp.refs[0].callee_id, callee_id);
        // no structural RefCall edge for the resolved ref (supersede)
        assert!(!resp.edges.iter().any(|e| e.kind == EdgeKind::RefCall));
    }

    // Fallback: a reference to a symbol with no in-corpus definition still emits
    // the best-effort enclosing → reference edge (dropped fail-closed downstream)
    // and no ScipRef.
    #[test]
    fn unresolved_ref_emits_fallback_edge_only() {
        let docs = vec![TextDocument {
            uri: "A.scala".to_string(),
            symbols: vec![
                sym("a/Caller#", KIND_CLASS),
                sym("a/Caller#call().", KIND_METHOD),
            ],
            occurrences: vec![
                occ("a/Caller#", 0, 2),
                occ("a/Caller#call().", 1, 2),
                // reference to an undefined symbol (not in def_ids)
                occ("z/Unknown#gone().", 5, 1),
            ],
        }];

        let resp = build_edges(&docs, "testcorpus");

        assert!(resp.refs.is_empty());
        let src = sdb_vname("a/Caller#call().", "A.scala", "testcorpus").id();
        let dst = sdb_vname("z/Unknown#gone().", "A.scala", "testcorpus").id();
        assert!(resp
            .edges
            .iter()
            .any(|e| e.src == src && e.dst == dst && e.kind == EdgeKind::RefCall));
    }

    #[test]
    fn noise_symbol_classification() {
        assert!(is_local_symbol("local0"));
        assert!(is_local_symbol("local42"));
        assert!(!is_local_symbol("locally")); // not a `local<digits>` symbol
        assert!(!is_local_symbol("a/Caller#call()."));
        assert!(is_parameter_descriptor("com/demo/Greeter#greet().(name)"));
        assert!(!is_parameter_descriptor("com/demo/Greeter#greet()."));
        assert!(!is_parameter_descriptor("com/demo/Greeter#"));
    }

    // A parameter descriptor and an anonymous local must not become nodes, refs,
    // or edges — mirroring the scip-reader filtering so scala stops leaking raw
    // `(name)` / `localN` symbols into the graph.
    #[test]
    fn parameter_and_local_symbols_are_dropped() {
        let docs = vec![TextDocument {
            uri: "Greeter.scala".to_string(),
            symbols: vec![
                sym("com/demo/Greeter#", KIND_CLASS),
                sym("com/demo/Greeter#greet().", KIND_METHOD),
                sym("com/demo/Greeter#greet().(name)", KIND_FIELD),
                sym("local0", KIND_FIELD),
            ],
            occurrences: vec![
                occ("com/demo/Greeter#", 0, 2),
                occ("com/demo/Greeter#greet().", 1, 2),
                // references to the parameter and to an anonymous local
                occ("com/demo/Greeter#greet().(name)", 1, 1),
                occ("local0", 1, 1),
            ],
        }];

        let resp = build_edges(&docs, "testcorpus");

        // Only the class and the method are nodes; no parameter / local node.
        assert_eq!(resp.nodes.len(), 2);
        assert!(resp.nodes.iter().all(
            |n| !n.vname.signature.contains("(name)") && !n.vname.signature.contains("local0")
        ));
        // No ref or edge points at the dropped symbols.
        assert!(resp.refs.is_empty());
        assert!(resp.edges.iter().all(|e| e.kind != EdgeKind::RefCall));
    }
}
