//! Travsr Phase B — Scala semantic analysis via SemanticDB.
//!
//! SemanticDB is built into the Scala compiler (scalac 2.13+ / Scala 3). This
//! sidecar injects a temporary sbt settings file enabling SemanticDB, runs
//! `sbt compile`, then parses the resulting `.semanticdb` protobuf files to
//! extract ref/call edges.
//!
//! Why not scip-scala? scip-scala is not published to any accessible registry
//! (Maven Central, Sonatype, or GitHub Releases) and cannot be installed
//! automatically. SemanticDB is a first-class feature of every modern sbt
//! project.
//!
//! ## Sandbox class: RequiresElevated (ADR-017 Rule 1)
//!
//! `sbt compile` resolves dependencies from Maven/sbt plugin repositories.
//!
//! ```text
//! travsr lang approve scala \
//!   --approved-by <pse-handle> \
//!   --reason "sbt dependency resolution for Scala semantic analysis" \
//!   --permitted-hosts repo1.maven.org,repo.maven.apache.org,repo.scala-sbt.org
//! travsr lang install scala
//! ```

use anyhow::Context as _;
use std::collections::{HashMap, VecDeque};
use std::io::Read;
use std::path::{Path, PathBuf};
use travsr_core::{Edge, EdgeKind, Node, VName};
use travsr_plugin_sdk::{
    run_plugin, InvokeRequest, InvokeResponse, ParseRequest, ParseResponse, Plugin,
};

const TIMEOUT_SECS: u64 = 600;
const SETTINGS_FILE: &str = ".travsr-semanticdb.sbt";
const SETTINGS_CONTENT: &str =
    "// Auto-generated by travsr Phase B — safe to delete.\nsemanticdbEnabled := true\n";

struct ScalaPhaseB;

impl Plugin for ScalaPhaseB {
    fn language(&self) -> travsr_core::Language {
        travsr_core::Language::Scala
    }
    fn extensions(&self) -> &[&str] {
        &["scala", "sc"]
    }
    fn supports_phase_b(&self) -> bool {
        sbt_available()
    }
    fn parse(&self, _req: &ParseRequest) -> ParseResponse {
        ParseResponse::default()
    }
    fn invoke_phase_b(&self, req: &InvokeRequest) -> InvokeResponse {
        match run_semanticdb(&req.root, req.corpus.as_str()) {
            Ok(resp) => resp,
            Err(e) => {
                tracing::warn!("semanticdb failed for {}: {e}", req.root.display());
                InvokeResponse::default()
            }
        }
    }
}

static SBT_BIN: std::sync::OnceLock<Option<PathBuf>> = std::sync::OnceLock::new();

fn find_sbt() -> Option<&'static PathBuf> {
    SBT_BIN
        .get_or_init(|| {
            // 1. PATH — filesystem scan avoids spawning sbt's JVM just for discovery
            if std::env::split_paths(&std::env::var_os("PATH").unwrap_or_default())
                .any(|d| d.join("sbt").exists())
            {
                return Some(PathBuf::from("sbt"));
            }
            let home = std::env::var_os("HOME").map(PathBuf::from)?;
            // 2. SDKMAN! — sdk install sbt
            let candidate = home.join(".sdkman/candidates/sbt/current/bin/sbt");
            if candidate.exists() {
                return Some(candidate);
            }
            // 3. Coursier on Linux — cs install sbt
            let candidate = home.join(".local/share/coursier/bin/sbt");
            if candidate.exists() {
                return Some(candidate);
            }
            // 4. Coursier on macOS
            let candidate = home.join("Library/Application Support/Coursier/bin/sbt");
            candidate.exists().then_some(candidate)
        })
        .as_ref()
}

fn sbt_available() -> bool {
    find_sbt().is_some()
}

/// Walk up to `max_depth` levels to find the directory containing `build.sbt`.
fn find_sbt_root(root: &Path, max_depth: usize) -> Option<PathBuf> {
    let mut queue: VecDeque<(PathBuf, usize)> = VecDeque::new();
    queue.push_back((root.to_path_buf(), 0));
    while let Some((dir, depth)) = queue.pop_front() {
        if dir.join("build.sbt").is_file() {
            return Some(dir);
        }
        if depth < max_depth {
            if let Ok(entries) = std::fs::read_dir(&dir) {
                for e in entries.flatten() {
                    let p = e.path();
                    if p.is_dir() {
                        let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                        if !matches!(name, "target" | ".git" | "node_modules" | ".travsr") {
                            queue.push_back((p, depth + 1));
                        }
                    }
                }
            }
        }
    }
    None
}

/// Walk `target/` collecting all `*.semanticdb` files (any depth).
fn find_semanticdb_files(sbt_root: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut queue: VecDeque<PathBuf> = VecDeque::new();
    queue.push_back(sbt_root.join("target"));
    while let Some(dir) = queue.pop_front() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                queue.push_back(p);
            } else if p.extension().and_then(|e| e.to_str()) == Some("semanticdb") {
                found.push(p);
            }
        }
    }
    found
}

fn run_semanticdb(root: &Path, corpus: &str) -> anyhow::Result<InvokeResponse> {
    let sbt_bin = find_sbt().ok_or_else(|| {
        anyhow::anyhow!(
            "sbt not found — install via SDKMAN! (sdk install sbt), \
             Coursier (cs install sbt), or Homebrew (brew install sbt)"
        )
    })?;

    let sbt_root = find_sbt_root(root, 4)
        .ok_or_else(|| anyhow::anyhow!("no build.sbt found under {}", root.display()))?;
    tracing::info!(sbt_root = %sbt_root.display(), "found sbt project root");

    let settings_path = sbt_root.join(SETTINGS_FILE);
    std::fs::write(&settings_path, SETTINGS_CONTENT)
        .with_context(|| format!("writing {}", settings_path.display()))?;

    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(TIMEOUT_SECS);
    let result = run_sbt_compile(&sbt_root, sbt_bin, deadline);

    let _ = std::fs::remove_file(&settings_path);

    let (status, stderr_out) = result?;
    anyhow::ensure!(
        status.success(),
        "sbt compile exited with {status}:\n{stderr_out}"
    );

    let semanticdb_files = find_semanticdb_files(&sbt_root);
    tracing::info!("found {} .semanticdb files", semanticdb_files.len());

    let mut all_docs = Vec::new();
    for path in &semanticdb_files {
        let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;
        all_docs.extend(parse_text_documents(&bytes));
    }

    Ok(build_edges(&all_docs, corpus))
}

fn run_sbt_compile(
    sbt_root: &Path,
    sbt_bin: &Path,
    deadline: std::time::Instant,
) -> anyhow::Result<(std::process::ExitStatus, String)> {
    let mut child = std::process::Command::new(sbt_bin)
        .arg("compile")
        .current_dir(sbt_root)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("failed to spawn sbt")?;

    let status = loop {
        match child.try_wait().context("polling sbt")? {
            Some(s) => break s,
            None if std::time::Instant::now() >= deadline => {
                let _ = child.kill();
                anyhow::bail!("sbt compile timed out after {TIMEOUT_SECS}s");
            }
            None => std::thread::sleep(std::time::Duration::from_millis(500)),
        }
    };

    let mut stderr_out = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = err.read_to_string(&mut stderr_out);
    }
    Ok((status, stderr_out))
}

// ── Minimal SemanticDB protobuf parser ───────────────────────────────────────
// SemanticDB file = serialised TextDocuments proto (wire format).
// We only decode fields needed for ref/call edge extraction.

#[derive(Debug, Default)]
struct TextDocument {
    uri: String,
    symbols: Vec<SymbolInfo>,
    occurrences: Vec<Occurrence>,
}

#[derive(Debug)]
struct SymbolInfo {
    symbol: String,
    kind: u32,
}

#[derive(Debug)]
struct Occurrence {
    start_line: u32,
    symbol: String,
    role: u32, // 1 = REFERENCE, 2 = DEFINITION
}

fn read_varint(data: &[u8], pos: &mut usize) -> Option<u64> {
    let mut result = 0u64;
    let mut shift = 0u32;
    loop {
        let b = *data.get(*pos)?;
        *pos += 1;
        result |= ((b & 0x7f) as u64) << shift;
        if b & 0x80 == 0 {
            return Some(result);
        }
        shift += 7;
        if shift >= 64 {
            return None;
        }
    }
}

fn skip_field(data: &[u8], pos: &mut usize, wire_type: u64) {
    match wire_type {
        0 => {
            read_varint(data, pos);
        }
        1 => *pos = pos.saturating_add(8).min(data.len()),
        2 => {
            if let Some(len) = read_varint(data, pos) {
                *pos = pos.saturating_add(len as usize).min(data.len());
            }
        }
        5 => *pos = pos.saturating_add(4).min(data.len()),
        _ => *pos = data.len(), // unknown wire type — stop parsing
    }
}

fn parse_range_start_line(data: &[u8]) -> u32 {
    let mut pos = 0;
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        if wtype == 0 {
            let val = read_varint(data, &mut pos).unwrap_or(0);
            if field == 1 {
                return val as u32;
            }
        } else {
            skip_field(data, &mut pos, wtype);
        }
    }
    0
}

fn parse_occurrence(data: &[u8]) -> Occurrence {
    let mut pos = 0;
    let mut occ = Occurrence {
        start_line: 0,
        symbol: String::new(),
        role: 0,
    };
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                // range
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                occ.start_line = parse_range_start_line(&data[pos..end]);
                pos = end;
            }
            (2, 2) => {
                // symbol string
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    occ.symbol = s.to_string();
                }
                pos = end;
            }
            (3, 0) => {
                // role
                occ.role = read_varint(data, &mut pos).unwrap_or(0) as u32;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    occ
}

fn parse_sym_info(data: &[u8]) -> SymbolInfo {
    let mut pos = 0;
    let mut info = SymbolInfo {
        symbol: String::new(),
        kind: 0,
    };
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    info.symbol = s.to_string();
                }
                pos = end;
            }
            (3, 0) => {
                info.kind = read_varint(data, &mut pos).unwrap_or(0) as u32;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    info
}

fn parse_text_document(data: &[u8]) -> TextDocument {
    let mut pos = 0;
    let mut doc = TextDocument::default();
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (2, 2) => {
                // uri
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                if let Ok(s) = std::str::from_utf8(&data[pos..end]) {
                    doc.uri = s.to_string();
                }
                pos = end;
            }
            (5, 2) => {
                // symbols (repeated SymbolInformation)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                doc.symbols.push(parse_sym_info(&data[pos..end]));
                pos = end;
            }
            (6, 2) => {
                // occurrences (repeated SymbolOccurrence)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                doc.occurrences.push(parse_occurrence(&data[pos..end]));
                pos = end;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    doc
}

fn parse_text_documents(data: &[u8]) -> Vec<TextDocument> {
    let mut pos = 0;
    let mut docs = Vec::new();
    while pos < data.len() {
        let Some(tag) = read_varint(data, &mut pos) else {
            break;
        };
        let field = (tag >> 3) as u32;
        let wtype = tag & 7;
        match (field, wtype) {
            (1, 2) => {
                // documents (repeated TextDocument)
                let len = read_varint(data, &mut pos).unwrap_or(0) as usize;
                let end = pos.saturating_add(len).min(data.len());
                docs.push(parse_text_document(&data[pos..end]));
                pos = end;
            }
            (_, wtype) => skip_field(data, &mut pos, wtype),
        }
    }
    docs
}

// ── Edge construction ─────────────────────────────────────────────────────────

// SemanticDB Kind enum values (scalameta/semanticdb.proto)
const KIND_FIELD: u32 = 2;
const KIND_METHOD: u32 = 3;
const KIND_OBJECT: u32 = 10;
const KIND_PACKAGE_OBJECT: u32 = 12;
const KIND_CLASS: u32 = 13;
const KIND_TRAIT: u32 = 14;
const KIND_MACRO: u32 = 22;

fn is_container_kind(kind: u32) -> bool {
    matches!(
        kind,
        KIND_FIELD
            | KIND_METHOD
            | KIND_OBJECT
            | KIND_PACKAGE_OBJECT
            | KIND_CLASS
            | KIND_TRAIT
            | KIND_MACRO
    )
}

fn kind_str(kind: u32) -> &'static str {
    match kind {
        KIND_FIELD => "field",
        KIND_METHOD | KIND_MACRO => "method",
        KIND_OBJECT | KIND_PACKAGE_OBJECT => "object",
        KIND_CLASS => "class",
        KIND_TRAIT => "trait",
        _ => "sym",
    }
}

fn is_stdlib_symbol(symbol: &str) -> bool {
    symbol.starts_with("scala/")
        || symbol.starts_with("java/")
        || symbol.starts_with("javax/")
        || symbol.starts_with("_root_/")
        || symbol.starts_with("android/")
}

fn sdb_vname(symbol: &str, path: &str, corpus: &str) -> VName {
    VName::new(corpus, "", path, "scala", format!("sdb:{symbol}"))
}

fn build_edges(docs: &[TextDocument], corpus: &str) -> InvokeResponse {
    let mut nodes = Vec::new();
    let mut edges = Vec::new();

    for doc in docs {
        let uri = &doc.uri;

        // symbol → kind map
        let kind_map: HashMap<&str, u32> = doc
            .symbols
            .iter()
            .map(|s| (s.symbol.as_str(), s.kind))
            .collect();

        // DEF occurrences for container symbols, sorted by start_line ascending
        let mut def_containers: Vec<(u32, &str)> = doc
            .occurrences
            .iter()
            .filter(|o| o.role == 2) // DEFINITION
            .filter(|o| {
                let kind = kind_map.get(o.symbol.as_str()).copied().unwrap_or(0);
                is_container_kind(kind)
            })
            .map(|o| (o.start_line, o.symbol.as_str()))
            .collect();
        def_containers.sort_by_key(|(line, _)| *line);

        // Emit a node for every user-defined symbol
        for sym in &doc.symbols {
            if is_stdlib_symbol(&sym.symbol) {
                continue;
            }
            let vname = sdb_vname(&sym.symbol, uri, corpus);
            nodes.push(
                Node::new(vname, kind_str(sym.kind)).with_line(
                    doc.occurrences
                        .iter()
                        .find(|o| o.role == 2 && o.symbol == sym.symbol)
                        .map(|o| o.start_line + 1) // 1-based
                        .unwrap_or(0),
                ),
            );
        }

        // ref/call edges: for each user REFERENCE find enclosing DEF container
        for occ in &doc.occurrences {
            if occ.role != 1 {
                continue; // only REFERENCEs
            }
            if is_stdlib_symbol(&occ.symbol) {
                continue;
            }

            // enclosing = last container DEF with start_line ≤ occ.start_line
            let Some((_, enc_sym)) = def_containers
                .iter()
                .rev()
                .find(|(line, _)| *line <= occ.start_line)
            else {
                continue;
            };

            if *enc_sym == occ.symbol {
                continue; // skip self-ref
            }

            let src_vname = sdb_vname(enc_sym, uri, corpus);
            let dst_vname = sdb_vname(&occ.symbol, uri, corpus);
            edges.push(Edge::new(src_vname.id(), dst_vname.id(), EdgeKind::RefCall));
        }
    }

    let edge_count = edges.len();
    let node_count = nodes.len();
    tracing::info!(
        nodes = node_count,
        edges = edge_count,
        "semanticdb: built graph"
    );

    InvokeResponse { nodes, edges }
}

fn main() {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("travsr_lang_scala=info".parse().unwrap()),
        )
        .init();

    run_plugin(ScalaPhaseB);
}
